(() => { const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)]; let capturedDescriptor=null, capturedPhoto=null, scanning=false, busy=false, activeCameraView=null;
const msg=(title,text,type='blue')=>{ $('#access-message').className=`mt-5 rounded-2xl border p-4 text-center ${type==='green'?'border-emerald-200 bg-emerald-50':type==='red'?'border-red-200 bg-red-50':type==='yellow'?'border-amber-200 bg-amber-50':'border-blue-100 bg-blue-50'}`; $('#access-message').innerHTML=`<p class="text-xs font-bold tracking-widest ${type==='green'?'text-emerald-700':type==='red'?'text-red-700':type==='yellow'?'text-amber-700':'text-blue-700'}">${title}</p><p class="mt-1 text-sm text-slate-600">${text}</p>`; };
function render(){ const students=Store.students(), logs=Store.logs(), today=new Date().toDateString(), todayLogs=logs.filter(l=>new Date(l.timestamp).toDateString()===today); const stats=[['ALUNOS CADASTRADOS',students.length],['ACESSOS HOJE',todayLogs.length],['AUTORIZADOS',todayLogs.filter(l=>l.status==='authorized').length],['NEGADOS',todayLogs.filter(l=>l.status==='denied').length]]; $('#metrics').innerHTML=stats.map(([a,b])=>`<div class="rounded-2xl bg-white p-4 shadow-panel"><p class="text-[10px] font-bold tracking-wider text-slate-500">${a}</p><p class="mt-1 text-2xl font-bold text-ink">${b}</p></div>`).join(''); $('#student-list').innerHTML=students.length?students.map(s=>`<article class="rounded-2xl bg-white p-5 shadow-panel"><span class="rounded-full bg-emerald-100 px-2 py-1 text-[10px] font-bold text-emerald-700">ROSTO CADASTRADO</span><h3 class="mt-3 font-bold text-ink">${esc(s.name)}</h3><p class="mt-1 text-sm text-slate-500">Matrícula: ${esc(s.registration)}<br>Turma: ${esc(s.class)}</p><button class="delete-student mt-4 text-sm font-bold text-red-600" data-id="${s.id}">EXCLUIR</button></article>`).join(''):'<p class="rounded-2xl bg-white p-6 text-slate-500 shadow-panel">Nenhum aluno cadastrado.</p>'; $('#history-list').innerHTML=logs.length?logs.map(l=>`<tr class="border-b border-slate-100"><td class="p-4">${new Date(l.timestamp).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</td><td>${esc(l.studentName)}</td><td>${esc(l.class || '—')}</td><td><span class="font-bold ${l.status==='authorized'?'text-emerald-600':'text-red-600'}">${l.status==='authorized'?'✓ AUTORIZADO':'✕ NEGADO'}</span></td></tr>`).join(''):'<tr><td class="p-5 text-slate-500" colspan="4">Nenhum acesso registrado.</td></tr>'; const last=logs[0]; $('#last-access').textContent=last?`${last.studentName} • ${new Date(last.timestamp).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})} • ${last.status==='authorized'?'Autorizado':'Negado'}`:'Nenhum acesso registrado hoje.'; }
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); function log(student,status){ const logs=Store.logs(), entry={id:crypto.randomUUID(),studentId:student?.id||null,studentName:student?.name||'Desconhecido',registration:student?.registration||'',class:student?.class||'',timestamp:new Date().toISOString(),status}; logs.unshift(entry); Store.saveLogs(logs.slice(0,100)); SupabaseAccessLogs.insert(entry).catch(()=>{}); render(); }
function gate(open){ $('#gate').classList.toggle('open',open); $('#gate-label').textContent=open?'CATRACA ABERTA':'CATRACA FECHADA'; }
function takePhoto(video) { const canvas=document.createElement('canvas'); const maxWidth=560, ratio=Math.min(1,maxWidth/video.videoWidth); canvas.width=Math.round(video.videoWidth*ratio); canvas.height=Math.round(video.videoHeight*ratio); canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height); return canvas.toDataURL('image/jpeg',.84); }
async function models(){ msg('PREPARANDO RECONHECIMENTO FACIAL...','Carregando modelos locais para esta sessão.'); try{await Face.load(); msg('AGUARDANDO','Posicione seu rosto diante da câmera.');}catch(e){msg('ERRO AO CARREGAR MODELOS',e.message,'red');throw e;} }
async function scan(){ if(!scanning||busy||!Face.ready) return; const video=$('#turn-video'); if(video.readyState<2){setTimeout(scan,500);return} try { const faces=await Face.detect(video); if(faces.length===0){msg('AGUARDANDO','Posicione seu rosto diante da câmera.');} else if(faces.length>1){msg('⚠ ATENÇÃO','Apenas uma pessoa deve estar diante da catraca.','yellow');} else { busy=true; msg('ROSTO DETECTADO','IDENTIFICANDO...'); setTimeout(()=>process(faces[0].descriptor),500); } } catch { msg('ERRO','Não foi possível analisar a imagem da câmera.','red'); } finally { if(!busy) setTimeout(scan,700); } }
function process(descriptor){ const student=Face.nearest(descriptor,Store.students()); if(student){ gate(true); msg('✓ ACESSO AUTORIZADO',`${esc(student.name)}<br>Matrícula: ${esc(student.registration)} • Turma: ${esc(student.class)}<br>Entrada registrada agora.`,'green'); log(student,'authorized'); } else { gate(false); msg('✕ ACESSO NEGADO','Pessoa não cadastrada. CATRACA BLOQUEADA.','red'); log(null,'denied'); } setTimeout(()=>{gate(false);msg('AGUARDANDO PRÓXIMO ACESSO','Posicione seu rosto diante da câmera.');busy=false;scan();},4500); }
function clearVideo(video){ video.pause(); video.srcObject=null; }
function stopTurn(message=true){ scanning=false; busy=false; if(activeCameraView==='turn') Camera.stop(); activeCameraView=null; clearVideo($('#turn-video')); $('#video-placeholder').classList.remove('hidden'); $('#turn-camera').disabled=false; $('#turn-camera').textContent='ATIVAR CÂMERA'; gate(false); if(message) msg('AGUARDANDO','Câmera desligada.'); }
async function startTurn(){ const button=$('#turn-camera'); try{ Camera.stop(); activeCameraView=null; button.disabled=true; button.textContent='INICIANDO...'; await Camera.start($('#turn-video')); activeCameraView='turn'; $('#video-placeholder').classList.add('hidden'); button.textContent='DESLIGAR CÂMERA'; await models(); scanning=true;scan(); } catch(e){ activeCameraView=null; clearVideo($('#turn-video')); $('#video-placeholder').classList.remove('hidden'); msg('CÂMERA INDISPONÍVEL',e.message,'red'); } finally { button.disabled=false; if(activeCameraView!=='turn') button.textContent='ATIVAR CÂMERA'; } }
$('#turn-camera').onclick=()=> activeCameraView==='turn' ? stopTurn() : startTurn();
$$('.nav-btn').forEach(b=>b.onclick=()=>{ $$('.nav-btn').forEach(x=>x.classList.remove('bg-white/15'));b.classList.add('bg-white/15');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active');$('#page-title').textContent=({turnstile:'Catraca',students:'Alunos',history:'Histórico',settings:'Configurações'})[b.dataset.view];render(); });
function stopRegister(){ if(activeCameraView==='register') Camera.stop(); activeCameraView=null; clearVideo($('#register-video')); $('#register-placeholder').classList.remove('hidden'); $('#register-camera').disabled=false; $('#register-camera').textContent='ATIVAR CÂMERA'; }
async function startRegister(){ const button=$('#register-camera'); try { Camera.stop(); activeCameraView=null; button.disabled=true; button.textContent='INICIANDO...'; await Camera.start($('#register-video')); activeCameraView='register'; $('#register-placeholder').classList.add('hidden'); await models(); $('#capture-status').textContent='Câmera pronta. Posicione apenas um rosto.'; button.textContent='DESLIGAR CÂMERA'; } catch(e){ activeCameraView=null; clearVideo($('#register-video')); $('#register-placeholder').classList.remove('hidden'); $('#capture-status').textContent=e.message; } finally { button.disabled=false; if(activeCameraView!=='register') button.textContent='ATIVAR CÂMERA'; } }
$('#open-register').onclick=()=>{ stopTurn(false); capturedDescriptor=null; capturedPhoto=null; $('#capture-status').textContent='Nenhum rosto capturado.'; $('#register-dialog').showModal(); }; $('#register-camera').onclick=()=> activeCameraView==='register' ? stopRegister() : startRegister(); $$('.close-dialog').forEach(b=>b.onclick=()=>{$('#register-dialog').close();stopRegister();});
$('#capture-face').onclick=async()=>{ try{if(activeCameraView!=='register') throw new Error('Ative a câmera antes de capturar o rosto.');if(!Face.ready)await models();const video=$('#register-video'),faces=await Face.detect(video); if(faces.length!==1) throw new Error(faces.length?'Apenas uma pessoa deve estar diante da câmera.':'Posicione seu rosto diante da câmera.');capturedDescriptor=Array.from(faces[0].descriptor);capturedPhoto=takePhoto(video);$('#capture-status').textContent='✓ Rosto e foto capturados com sucesso.';}catch(e){$('#capture-status').textContent=e.message;} };
$('#student-form').onsubmit=async e=>{e.preventDefault();if(!capturedDescriptor){$('#capture-status').textContent='Capture um rosto antes de salvar.';return}const f=new FormData(e.target),students=Store.students(),student={id:crypto.randomUUID(),name:f.get('name').trim(),registration:f.get('registration').trim(),class:f.get('class').trim(),faceDescriptor:capturedDescriptor,photoData:capturedPhoto};$('#capture-status').textContent='Salvando cadastro...';try { student.photoUrl=await SupabasePhotos.upload(student.id,capturedPhoto); delete student.photoData; $('#capture-status').textContent='✓ Foto salva no Supabase.'; } catch { $('#capture-status').textContent='Foto salva somente neste navegador (configure o bucket do Supabase para sincronizar).'; } students.push(student);Store.saveStudents(students);capturedDescriptor=null;capturedPhoto=null;e.target.reset();setTimeout(()=>{$('#register-dialog').close();stopRegister();render();},500);};
async function loadRemoteHistory(){ try { const remote=await SupabaseAccessLogs.getAll(), local=Store.logs(), combined=[...remote,...local.filter(localLog=>!remote.some(remoteLog=>remoteLog.id===localLog.id))].sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp)).slice(0,100); Store.saveLogs(combined); render(); } catch { /* A aplicação continua funcional sem conexão ou sem a tabela configurada. */ } }
$('#student-list').onclick=e=>{const id=e.target.dataset.id;if(id&&confirm('Excluir este aluno?')){Store.saveStudents(Store.students().filter(s=>s.id!==id));render();}}; $('#clear-history').onclick=()=>{if(confirm('Limpar todo o histórico?')){Store.saveLogs([]);SupabaseAccessLogs.clear().catch(()=>{});render();}}; window.addEventListener('beforeunload',()=>Camera.stop()); render(); loadRemoteHistory();
})();
